/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as NegotiationRouteImport } from './routes/negotiation'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiGameStatusRouteImport } from './routes/api/game/status'
import { Route as ApiGameStateRouteImport } from './routes/api/game/state'
import { Route as ApiGameRetreatRouteImport } from './routes/api/game/retreat'
import { Route as ApiGameResolveRouteImport } from './routes/api/game/resolve'
import { Route as ApiGameResetRouteImport } from './routes/api/game/reset'
import { Route as ApiGameOrdersRouteImport } from './routes/api/game/orders'
import { Route as ApiGameBuildRouteImport } from './routes/api/game/build'
import { Route as ApiChatChannelsRouteImport } from './routes/api/chat/channels'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as ApiGamePlayerPlayerIdRouteImport } from './routes/api/game/player.$playerId'
import { Route as ApiChatChannelsIdMessagesRouteImport } from './routes/api/chat/channels.$id.messages'
import { Route as ApiChatChannelsIdLeaveRouteImport } from './routes/api/chat/channels.$id.leave'
import { Route as ApiChatChannelsIdJoinRouteImport } from './routes/api/chat/channels.$id.join'
import { Route as ApiChatChannelsIdInviteRouteImport } from './routes/api/chat/channels.$id.invite'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationRoute = NegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiGameStatusRoute = ApiGameStatusRouteImport.update({
  id: '/api/game/status',
  path: '/api/game/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameStateRoute = ApiGameStateRouteImport.update({
  id: '/api/game/state',
  path: '/api/game/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRetreatRoute = ApiGameRetreatRouteImport.update({
  id: '/api/game/retreat',
  path: '/api/game/retreat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameResolveRoute = ApiGameResolveRouteImport.update({
  id: '/api/game/resolve',
  path: '/api/game/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameResetRoute = ApiGameResetRouteImport.update({
  id: '/api/game/reset',
  path: '/api/game/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameOrdersRoute = ApiGameOrdersRouteImport.update({
  id: '/api/game/orders',
  path: '/api/game/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameBuildRoute = ApiGameBuildRouteImport.update({
  id: '/api/game/build',
  path: '/api/game/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatChannelsRoute = ApiChatChannelsRouteImport.update({
  id: '/api/chat/channels',
  path: '/api/chat/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const ApiGamePlayerPlayerIdRoute = ApiGamePlayerPlayerIdRouteImport.update({
  id: '/api/game/player/$playerId',
  path: '/api/game/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatChannelsIdMessagesRoute =
  ApiChatChannelsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiChatChannelsRoute,
  } as any)
const ApiChatChannelsIdLeaveRoute = ApiChatChannelsIdLeaveRouteImport.update({
  id: '/$id/leave',
  path: '/$id/leave',
  getParentRoute: () => ApiChatChannelsRoute,
} as any)
const ApiChatChannelsIdJoinRoute = ApiChatChannelsIdJoinRouteImport.update({
  id: '/$id/join',
  path: '/$id/join',
  getParentRoute: () => ApiChatChannelsRoute,
} as any)
const ApiChatChannelsIdInviteRoute = ApiChatChannelsIdInviteRouteImport.update({
  id: '/$id/invite',
  path: '/$id/invite',
  getParentRoute: () => ApiChatChannelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/negotiation': typeof NegotiationRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/chat/channels': typeof ApiChatChannelsRouteWithChildren
  '/api/game/build': typeof ApiGameBuildRoute
  '/api/game/orders': typeof ApiGameOrdersRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/game/resolve': typeof ApiGameResolveRoute
  '/api/game/retreat': typeof ApiGameRetreatRoute
  '/api/game/state': typeof ApiGameStateRoute
  '/api/game/status': typeof ApiGameStatusRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/game/player/$playerId': typeof ApiGamePlayerPlayerIdRoute
  '/api/chat/channels/$id/invite': typeof ApiChatChannelsIdInviteRoute
  '/api/chat/channels/$id/join': typeof ApiChatChannelsIdJoinRoute
  '/api/chat/channels/$id/leave': typeof ApiChatChannelsIdLeaveRoute
  '/api/chat/channels/$id/messages': typeof ApiChatChannelsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/negotiation': typeof NegotiationRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/chat/channels': typeof ApiChatChannelsRouteWithChildren
  '/api/game/build': typeof ApiGameBuildRoute
  '/api/game/orders': typeof ApiGameOrdersRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/game/resolve': typeof ApiGameResolveRoute
  '/api/game/retreat': typeof ApiGameRetreatRoute
  '/api/game/state': typeof ApiGameStateRoute
  '/api/game/status': typeof ApiGameStatusRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/game/player/$playerId': typeof ApiGamePlayerPlayerIdRoute
  '/api/chat/channels/$id/invite': typeof ApiChatChannelsIdInviteRoute
  '/api/chat/channels/$id/join': typeof ApiChatChannelsIdJoinRoute
  '/api/chat/channels/$id/leave': typeof ApiChatChannelsIdLeaveRoute
  '/api/chat/channels/$id/messages': typeof ApiChatChannelsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/negotiation': typeof NegotiationRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/chat/channels': typeof ApiChatChannelsRouteWithChildren
  '/api/game/build': typeof ApiGameBuildRoute
  '/api/game/orders': typeof ApiGameOrdersRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/game/resolve': typeof ApiGameResolveRoute
  '/api/game/retreat': typeof ApiGameRetreatRoute
  '/api/game/state': typeof ApiGameStateRoute
  '/api/game/status': typeof ApiGameStatusRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/game/player/$playerId': typeof ApiGamePlayerPlayerIdRoute
  '/api/chat/channels/$id/invite': typeof ApiChatChannelsIdInviteRoute
  '/api/chat/channels/$id/join': typeof ApiChatChannelsIdJoinRoute
  '/api/chat/channels/$id/leave': typeof ApiChatChannelsIdLeaveRoute
  '/api/chat/channels/$id/messages': typeof ApiChatChannelsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/negotiation'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/chat/channels'
    | '/api/game/build'
    | '/api/game/orders'
    | '/api/game/reset'
    | '/api/game/resolve'
    | '/api/game/retreat'
    | '/api/game/state'
    | '/api/game/status'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/api/game/player/$playerId'
    | '/api/chat/channels/$id/invite'
    | '/api/chat/channels/$id/join'
    | '/api/chat/channels/$id/leave'
    | '/api/chat/channels/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/negotiation'
    | '/redirect'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/chat/channels'
    | '/api/game/build'
    | '/api/game/orders'
    | '/api/game/reset'
    | '/api/game/resolve'
    | '/api/game/retreat'
    | '/api/game/state'
    | '/api/game/status'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/api/game/player/$playerId'
    | '/api/chat/channels/$id/invite'
    | '/api/chat/channels/$id/join'
    | '/api/chat/channels/$id/leave'
    | '/api/chat/channels/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/customScript.js'
    | '/deferred'
    | '/negotiation'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/chat/channels'
    | '/api/game/build'
    | '/api/game/orders'
    | '/api/game/reset'
    | '/api/game/resolve'
    | '/api/game/retreat'
    | '/api/game/state'
    | '/api/game/status'
    | '/api/users/$userId'
    | '/posts_/$postId/deep'
    | '/api/game/player/$playerId'
    | '/api/chat/channels/$id/invite'
    | '/api/chat/channels/$id/join'
    | '/api/chat/channels/$id/leave'
    | '/api/chat/channels/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  NegotiationRoute: typeof NegotiationRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiChatChannelsRoute: typeof ApiChatChannelsRouteWithChildren
  ApiGameBuildRoute: typeof ApiGameBuildRoute
  ApiGameOrdersRoute: typeof ApiGameOrdersRoute
  ApiGameResetRoute: typeof ApiGameResetRoute
  ApiGameResolveRoute: typeof ApiGameResolveRoute
  ApiGameRetreatRoute: typeof ApiGameRetreatRoute
  ApiGameStateRoute: typeof ApiGameStateRoute
  ApiGameStatusRoute: typeof ApiGameStatusRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
  ApiGamePlayerPlayerIdRoute: typeof ApiGamePlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiation': {
      id: '/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof NegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/game/status': {
      id: '/api/game/status'
      path: '/api/game/status'
      fullPath: '/api/game/status'
      preLoaderRoute: typeof ApiGameStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/state': {
      id: '/api/game/state'
      path: '/api/game/state'
      fullPath: '/api/game/state'
      preLoaderRoute: typeof ApiGameStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/retreat': {
      id: '/api/game/retreat'
      path: '/api/game/retreat'
      fullPath: '/api/game/retreat'
      preLoaderRoute: typeof ApiGameRetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/resolve': {
      id: '/api/game/resolve'
      path: '/api/game/resolve'
      fullPath: '/api/game/resolve'
      preLoaderRoute: typeof ApiGameResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/reset': {
      id: '/api/game/reset'
      path: '/api/game/reset'
      fullPath: '/api/game/reset'
      preLoaderRoute: typeof ApiGameResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/orders': {
      id: '/api/game/orders'
      path: '/api/game/orders'
      fullPath: '/api/game/orders'
      preLoaderRoute: typeof ApiGameOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/build': {
      id: '/api/game/build'
      path: '/api/game/build'
      fullPath: '/api/game/build'
      preLoaderRoute: typeof ApiGameBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/channels': {
      id: '/api/chat/channels'
      path: '/api/chat/channels'
      fullPath: '/api/chat/channels'
      preLoaderRoute: typeof ApiChatChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/api/game/player/$playerId': {
      id: '/api/game/player/$playerId'
      path: '/api/game/player/$playerId'
      fullPath: '/api/game/player/$playerId'
      preLoaderRoute: typeof ApiGamePlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/channels/$id/messages': {
      id: '/api/chat/channels/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/chat/channels/$id/messages'
      preLoaderRoute: typeof ApiChatChannelsIdMessagesRouteImport
      parentRoute: typeof ApiChatChannelsRoute
    }
    '/api/chat/channels/$id/leave': {
      id: '/api/chat/channels/$id/leave'
      path: '/$id/leave'
      fullPath: '/api/chat/channels/$id/leave'
      preLoaderRoute: typeof ApiChatChannelsIdLeaveRouteImport
      parentRoute: typeof ApiChatChannelsRoute
    }
    '/api/chat/channels/$id/join': {
      id: '/api/chat/channels/$id/join'
      path: '/$id/join'
      fullPath: '/api/chat/channels/$id/join'
      preLoaderRoute: typeof ApiChatChannelsIdJoinRouteImport
      parentRoute: typeof ApiChatChannelsRoute
    }
    '/api/chat/channels/$id/invite': {
      id: '/api/chat/channels/$id/invite'
      path: '/$id/invite'
      fullPath: '/api/chat/channels/$id/invite'
      preLoaderRoute: typeof ApiChatChannelsIdInviteRouteImport
      parentRoute: typeof ApiChatChannelsRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiChatChannelsRouteChildren {
  ApiChatChannelsIdInviteRoute: typeof ApiChatChannelsIdInviteRoute
  ApiChatChannelsIdJoinRoute: typeof ApiChatChannelsIdJoinRoute
  ApiChatChannelsIdLeaveRoute: typeof ApiChatChannelsIdLeaveRoute
  ApiChatChannelsIdMessagesRoute: typeof ApiChatChannelsIdMessagesRoute
}

const ApiChatChannelsRouteChildren: ApiChatChannelsRouteChildren = {
  ApiChatChannelsIdInviteRoute: ApiChatChannelsIdInviteRoute,
  ApiChatChannelsIdJoinRoute: ApiChatChannelsIdJoinRoute,
  ApiChatChannelsIdLeaveRoute: ApiChatChannelsIdLeaveRoute,
  ApiChatChannelsIdMessagesRoute: ApiChatChannelsIdMessagesRoute,
}

const ApiChatChannelsRouteWithChildren = ApiChatChannelsRoute._addFileChildren(
  ApiChatChannelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  NegotiationRoute: NegotiationRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiChatChannelsRoute: ApiChatChannelsRouteWithChildren,
  ApiGameBuildRoute: ApiGameBuildRoute,
  ApiGameOrdersRoute: ApiGameOrdersRoute,
  ApiGameResetRoute: ApiGameResetRoute,
  ApiGameResolveRoute: ApiGameResolveRoute,
  ApiGameRetreatRoute: ApiGameRetreatRoute,
  ApiGameStateRoute: ApiGameStateRoute,
  ApiGameStatusRoute: ApiGameStatusRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
  ApiGamePlayerPlayerIdRoute: ApiGamePlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
